//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeRegistrationAndListing.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int empId { get; set; }
        public string empStatus { get; set; }
        public Nullable<int> sssNum { get; set; }
        public Nullable<int> tinNum { get; set; }
        public Nullable<System.DateTime> dateEmployed { get; set; }
        public Nullable<System.DateTime> dateFrom { get; set; }
        public Nullable<System.DateTime> dateTo { get; set; }
        public byte[] Signature { get; set; }
        public string userName { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public byte[] Image { get; set; }
        public string fName { get; set; }
        public string mName { get; set; }
        public string Lname { get; set; }
        public Nullable<System.DateTime> birthDate { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public Nullable<int> contactNo { get; set; }
    }
}
