//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeRegistrationAndListing
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table
    {
        public int employeeId { get; set; }
        public string firstName { get; set; }
        public string middleName { get; set; }
        public string lastName_ { get; set; }
        public System.DateTime birthDate { get; set; }
        public string emergencyName { get; set; }
        public string emergencyAddress { get; set; }
        public decimal emergencyContact { get; set; }
        public decimal sssnumber { get; set; }
        public decimal tinnumber { get; set; }
        public System.DateTime dateEmployed { get; set; }
        public string userName { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public string confirmEmail { get; set; }
        public string confirmPassword { get; set; }
    }
}
